[package]
name = "ui"
version = "0.1.0"
authors = ["risboo6909 <risboo6909@yandex-team.ru>"]

[dependencies]
piston_window = "0.60.*"
piston2d-opengl_graphics = "0.36.*"
engine = { path = "../engine" }
